server:
  port: 8075
springdoc:
  packages-to-scan: com.righttek.es.plantillanotificacion.controller
  pathsToMatch: /v1, /api/es/plantillaNotificacion/**

# CONECCION A BASE DE DATOS
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/GOTALENT
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
          non_contextual_creation: true